/*
SQLyog Ultimate v12.14 (64 bit)
MySQL - 10.4.19-MariaDB-log : Database - itlog
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
USE `itlog`;

/*Table structure for table `lesson` */

DROP TABLE IF EXISTS `lesson`;

CREATE TABLE `lesson` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `video` varchar(255) NOT NULL,
  `learned` int(2) DEFAULT 0,
  `created_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8;

/*Data for the table `lesson` */

insert  into `lesson`(`id`,`title`,`description`,`video`,`learned`,`created_at`,`created_by`) values 
(1,'Geosynchronous Orbits are WEIRD','Go to https://givewell.org/minutephysics to have your first donation matched up to $100!\r\n\r\nThis video is about the physics of geosynchronous and geostationary orbits, why they exist, when they don\'t, when they\'re useful for communication/satellite TV, etc.\r\n\r\nREFERENCES\r\n\r\nFraction of a sphere that\'s visible from a given distance\r\nhttps://math.stackexchange.com/questi...\r\n\r\nOrbital period\r\nhttps://en.wikipedia.org/wiki/Orbital...\r\n\r\nKepler\'s third law\r\nhttps://en.wikipedia.org/wiki/Kepler%...\r\n\r\n\r\nThere is a limit (kind of like the Roche limit but for rotations). A rotating solid steel ball or other chunk of metal that has tensile strength (ie that isn\'t just a pile of stuff held together by gravity like most planets) would be able to spin faster.\r\n\r\nCalculate how much of a planet\'s surface you can see from a given geosynchronous orbit/radius? (Obviously for lower ones you can see less, etc) - d/(2(R+d)) where d is distance to surface, ie, R is sphere radius, R+d is object radius from sphere center.','tI8OqpkOVzs',1,'2023-04-20 18:39:41',100),
(2,'Fixing YOUR Sleep | Sleeping With Friends','How much sleep did you get last night? None? Huh. Neither did we. We were just putting the finishing touches on this competition show we made about sleep science. \r\nWho’s the deeper sleeper? Whose snooze will lose? Greg Brown and Melissa Maribel face off to find out in the premier episode of Sleeping with Friends, a new BrainCraft series where reality meets science, hosted by Vanessa Hill. \r\n\r\nIn the next two episodes, YouTube Creators will go head to head to see who can improve their sleep the most. Our expert judges will determine who slept best and use science to tell us why. ','kVDHsMx78wk',1,'2023-04-20 18:40:02',100),
(3,'JK Wedding Entrance Dance','I think the reason people gravitate to this video--the reason it went viral in the first place, before \"The Office\"--is because it\'s so clearly a genuine expression of friendship and joy. So many weddings are these huge, overblown extravaganzas that cost a jillion dollars and stress everyone out. This wedding had simple flowers, simple clothes, an undecorated church','4-94JhLEiN0',1,'2023-04-20 18:43:44',100),
(4,'Volunteer Of War','After my phone got stolen, I quickly realized just how much of my personal information and data the thief had instantly obtained. So, I let another phone get stolen. This time my phone was pre-programmed with spyware so I could keep tabs on the thief in order to get to know him. However, to what extent is it possible to truly get to know someone by going through the content of their phone?\r\n\r\nIn the Netherlands, 300 police reports a week are filed for smartphone-theft. Besides losing your expensive device, a stranger has access to all of your photos, videos, e-mails, messages and contacts.\r\n\r\nYet, what kind of person steals a phone? And where do stolen phones eventually end up?\r\n\r\nThe short documentary ‘Find My Phone’ follows a stolen phone’s second life by means of using spyware.\r\n\r\nAlthough you’ll meet the person behind the theft up close and personal, the question remains: how well can you actually get to know someone when you base yourself on the information retrieved from their phone?\r\n\r\nDo you want the full story behind the film? You can contact me in order to answer all of your questions by means of an interview (I’m proficient in Dutch and English), or to invite me to a film festival.\r\n\r\nTo use this video in a commercial player or in broadcasts, please email licensing@storyful.com','NpN9NzO4Mo8',0,'2023-04-20 17:56:48',100),
(5,'How to do AMAZING Card Trick! [SPELL The NAME of Your Card!]','A mind blowing and simple card trick! Imagine shuffling cards then having someone spell the name of the card they chose! Simple magic trick at it\'s finest. Simple is sometimes better! No skill required! Subscribe Now for more Pranks, Tricks, Social Experiments and Fun Videos: http://bit.ly/ucmagic\r\n\r\nIf you like card tricks, sleight of hand, mind reading, mentalism, street magic, bar tricks, bets, challenges, money magic and more, be sure to look through this channel. We have thousands of magic tutorials for you. \r\n\r\n#magic #cardtrick #howto','DG7UsEtrj58',0,'2023-04-20 17:59:05',100),
(6,'Noah takes a photo of himself every day for 6 years.','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','6B26asyGKDo',0,'2023-04-20 18:02:06',100),
(7,'Self Driving Mercedes: Behind the Wheel!','Mercedes\' Autonomous car tech at CES 2017!\r\n\r\nThe Tesla playlist:   \r\n\r\n • Tesla  \r\n\r\nVideo Gear I use: http://kit.com/MKBHD/video-gear#recom...\r\n\r\nIntro Track: Ongoing Thing by 20syl, Oddisee\r\n\r\n~\r\nhttp://twitter.com/MKBHD\r\nhttp://snapchat.com/add/MKBHD\r\nhttp://google.com/+MarquesBrownlee\r\nhttp://instagram.com/MKBHD\r\nhttp://facebook.com/MKBHD','XIzimkcuEuk',0,'2023-04-20 18:03:03',100),
(8,'Rebels Of Eternity\r\n\r\n','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','6B26asyGKDo',0,'2023-04-20 18:02:06',100),
(9,'Fixing YOUR Sleep | Sleeping With Friends','How much sleep did you get last night? None? Huh. Neither did we. We were just putting the finishing touches on this competition show we made about sleep science. \r\nWho’s the deeper sleeper? Whose snooze will lose? Greg Brown and Melissa Maribel face off to find out in the premier episode of Sleeping with Friends, a new BrainCraft series where reality meets science, hosted by Vanessa Hill. \r\n\r\nIn the next two episodes, YouTube Creators will go head to head to see who can improve their sleep the most. Our expert judges will determine who slept best and use science to tell us why. ','kVDHsMx78wk',0,'2023-04-19 17:54:07',100),
(10,'Strangers And Men','After my phone got stolen, I quickly realized just how much of my personal information and data the thief had instantly obtained. So, I let another phone get stolen. This time my phone was pre-programmed with spyware so I could keep tabs on the thief in order to get to know him. However, to what extent is it possible to truly get to know someone by going through the content of their phone?\r\n\r\nIn the Netherlands, 300 police reports a week are filed for smartphone-theft. Besides losing your expensive device, a stranger has access to all of your photos, videos, e-mails, messages and contacts.\r\n\r\nYet, what kind of person steals a phone? And where do stolen phones eventually end up?\r\n\r\nThe short documentary ‘Find My Phone’ follows a stolen phone’s second life by means of using spyware.\r\n\r\nAlthough you’ll meet the person behind the theft up close and personal, the question remains: how well can you actually get to know someone when you base yourself on the information retrieved from their phone?\r\n\r\nDo you want the full story behind the film? You can contact me in order to answer all of your questions by means of an interview (I’m proficient in Dutch and English), or to invite me to a film festival.\r\n\r\nTo use this video in a commercial player or in broadcasts, please email licensing@storyful.com','NpN9NzO4Mo8',0,'2023-04-20 17:56:48',100),
(11,'Commander Of Space','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','6B26asyGKDo',0,'2023-04-20 18:02:06',100),
(12,'Women Of The Past\r\n\r\n','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','B26asyGKDo',0,'2023-04-20 18:02:06',100),
(13,'How to do AMAZING Card Trick! [SPELL The NAME of Your Card!]','A mind blowing and simple card trick! Imagine shuffling cards then having someone spell the name of the card they chose! Simple magic trick at it\'s finest. Simple is sometimes better! No skill required! Subscribe Now for more Pranks, Tricks, Social Experiments and Fun Videos: http://bit.ly/ucmagic\r\n\r\nIf you like card tricks, sleight of hand, mind reading, mentalism, street magic, bar tricks, bets, challenges, money magic and more, be sure to look through this channel. We have thousands of magic tutorials for you. \r\n\r\n#magic #cardtrick #howto','DG7UsEtrj58',0,'2023-04-20 17:59:05',100),
(14,'Agents Of Our Legacy','After my phone got stolen, I quickly realized just how much of my personal information and data the thief had instantly obtained. So, I let another phone get stolen. This time my phone was pre-programmed with spyware so I could keep tabs on the thief in order to get to know him. However, to what extent is it possible to truly get to know someone by going through the content of their phone?\r\n\r\nIn the Netherlands, 300 police reports a week are filed for smartphone-theft. Besides losing your expensive device, a stranger has access to all of your photos, videos, e-mails, messages and contacts.\r\n\r\nYet, what kind of person steals a phone? And where do stolen phones eventually end up?\r\n\r\nThe short documentary ‘Find My Phone’ follows a stolen phone’s second life by means of using spyware.\r\n\r\nAlthough you’ll meet the person behind the theft up close and personal, the question remains: how well can you actually get to know someone when you base yourself on the information retrieved from their phone?\r\n\r\nDo you want the full story behind the film? You can contact me in order to answer all of your questions by means of an interview (I’m proficient in Dutch and English), or to invite me to a film festival.\r\n\r\nTo use this video in a commercial player or in broadcasts, please email licensing@storyful.com','NpN9NzO4Mo8',0,'2023-04-20 17:56:48',100),
(15,'Short Film: Find my Phone - Subtitled','After my phone got stolen, I quickly realized just how much of my personal information and data the thief had instantly obtained. So, I let another phone get stolen. This time my phone was pre-programmed with spyware so I could keep tabs on the thief in order to get to know him. However, to what extent is it possible to truly get to know someone by going through the content of their phone?\r\n\r\nIn the Netherlands, 300 police reports a week are filed for smartphone-theft. Besides losing your expensive device, a stranger has access to all of your photos, videos, e-mails, messages and contacts.\r\n\r\nYet, what kind of person steals a phone? And where do stolen phones eventually end up?\r\n\r\nThe short documentary ‘Find My Phone’ follows a stolen phone’s second life by means of using spyware.\r\n\r\nAlthough you’ll meet the person behind the theft up close and personal, the question remains: how well can you actually get to know someone when you base yourself on the information retrieved from their phone?\r\n\r\nDo you want the full story behind the film? You can contact me in order to answer all of your questions by means of an interview (I’m proficient in Dutch and English), or to invite me to a film festival.\r\n\r\nTo use this video in a commercial player or in broadcasts, please email licensing@storyful.com','NpN9NzO4Mo8',0,'2023-04-20 17:56:48',100),
(16,'Stranger Of Our Destiny','How much sleep did you get last night? None? Huh. Neither did we. We were just putting the finishing touches on this competition show we made about sleep science. \r\nWho’s the deeper sleeper? Whose snooze will lose? Greg Brown and Melissa Maribel face off to find out in the premier episode of Sleeping with Friends, a new BrainCraft series where reality meets science, hosted by Vanessa Hill. \r\n\r\nIn the next two episodes, YouTube Creators will go head to head to see who can improve their sleep the most. Our expert judges will determine who slept best and use science to tell us why. ','kVDHsMx78wk',0,'2023-04-19 17:54:07',100),
(17,'How to do AMAZING Card Trick! [SPELL The NAME of Your Card!]','A mind blowing and simple card trick! Imagine shuffling cards then having someone spell the name of the card they chose! Simple magic trick at it\'s finest. Simple is sometimes better! No skill required! Subscribe Now for more Pranks, Tricks, Social Experiments and Fun Videos: http://bit.ly/ucmagic\r\n\r\nIf you like card tricks, sleight of hand, mind reading, mentalism, street magic, bar tricks, bets, challenges, money magic and more, be sure to look through this channel. We have thousands of magic tutorials for you. \r\n\r\n#magic #cardtrick #howto','DG7UsEtrj58',0,'2023-04-20 17:59:05',100),
(18,'Guardian Of The Crash','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','6B26asyGKDo',0,'2023-04-20 18:02:06',100),
(19,'Strangers In The Center Of The Earth','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','NpN9NzO4Mo8',0,'2023-04-20 18:02:06',100),
(20,'Heroes Of The Universe','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','6B26asyGKDo',0,'2023-04-20 18:02:06',100),
(21,'Intruders','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','DG7UsEtrj58',1,'2023-04-20 18:37:40',100),
(22,'Creators Of Time','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','NpN9NzO4Mo8',0,'2023-04-20 18:02:06',100),
(23,'Commanders Of Honor','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','kVDHsMx78wk',0,'2023-04-20 18:02:06',100),
(24,'Pilots Of The Ocean','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','6B26asyGKDo',0,'2023-04-20 18:02:06',100),
(25,'Medic Of Our Legacy\r\n\r\n','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','DG7UsEtrj58',0,'2023-04-20 18:02:06',100),
(26,'Courage For The End Of The Sun','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','6B26asyGKDo',0,'2023-04-20 18:02:06',100),
(27,'Alive On Outer Space','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','6B26asyGKDo',0,'2023-04-20 18:02:06',100),
(28,'Revenge Of Earth\'s Legacy','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','NpN9NzO4Mo8',0,'2023-04-20 18:02:06',100),
(29,'Commander Of Space','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','tI8OqpkOVzs',0,'2023-04-20 18:02:06',100),
(30,'Revenge Of Earth\'s Legacy','This video gives me goosebumps because It makes me realize how fast time goes by, and how you can\'t do anything about it. and just by looking at this guy\'s eyes, he gets more sad each time. It makes me wonder what he\'s been through.','tI8OqpkOVzs',0,'2023-04-20 18:02:06',100);

/*Table structure for table `migration` */

DROP TABLE IF EXISTS `migration`;

CREATE TABLE `migration` (
  `version` varchar(180) NOT NULL,
  `apply_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `migration` */

insert  into `migration`(`version`,`apply_time`) values 
('m000000_000000_base',1681985874),
('m230420_101501_create_lesson_table',1681985877);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
